spring.application.name=naon

spring.datasource.url=jdbc:mariadb://db.wisejia.com:3303/naon
spring.datasource.username=naon
spring.datasource.password=NaoN0829
spring.datasource.driverClassName=org.mariadb.jdbc.Driver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

home.key = nYtwbIIbs0HcX5vK2xYeYhnIOODvjsF9+W0YMMui3IYGUcLHGjD0AAayOJ8YJVLDq/R1aftI9qPymJjaYyY2vA==
tour.key = nYtwbIIbs0HcX5vK2xYeYhnIOODvjsF9%2BW0YMMui3IYGUcLHGjD0AAayOJ8YJVLDq%2FR1aftI9qPymJjaYyY2vA%3D%3D

# open api
open-api.Url=https://apis.data.go.kr/6260000/FoodService/getFoodKr
open-api.Key=j41xqN6GvHptLx3L%2Bl%2Fl2qW6tUgIcuzmfn9cPxw4rxq8XhKMK0mr1GW5b6ImDL%2BUIDTrF35gteGKLO0%2FzG2T2g%3D%3D
